# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Thurston for Secretary of State
description: Campaign to elect John Thurston as Secretary of State for Arkansas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnthurston.net" # the base hostname & protocol for your site
permalink: /:title/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - gulpfile.js
  - _assets
  
# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
